public void testAxisAngle_failAssert0() throws Exception {
        try {
            Rotation r = new Rotation(new Vector3D(10, 10, 10), (2 * Math.PI) / 3);
            r.applyTo(Vector3D.plusI);
            r.applyTo(Vector3D.plusJ);
            r.applyTo(Vector3D.plusK);
            double s = 1 / Math.sqrt(3);
            r.getAxis();
            new Vector3D(s, s, s);
            r.getAngle();
            double double_0 = (2 * Math.PI) / 3;
            {
                new Rotation(new Vector3D(0, 0, 0), (2 * Math.PI) / 3);
            }
            r = new Rotation(Vector3D.plusK, 1.5 * Math.PI);
            r.getAxis();
            new Vector3D(0, 0, -1);
            r.getAngle();
            double double_1 = 0.5 * Math.PI;
            r = new Rotation(Vector3D.plusJ, Math.PI);
            r.getAxis();
            r.getAngle();

            TestCase.fail("testAxisAngle should have thrown ArithmeticException");
        } catch (ArithmeticException expected) {
            TestCase.assertEquals("null norm", expected.getMessage());
        }
    }